# Generated by Django 5.0.3 on 2024-04-03 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='screen',
        ),
        migrations.AddField(
            model_name='seat',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='theatre.show'),
        ),
    ]
