# Generated by Django 5.0.3 on 2024-04-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0004_remove_seat_screen_seat_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='number',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='row',
        ),
        migrations.AddField(
            model_name='seat',
            name='seatNo',
            field=models.CharField(default='A0', max_length=3),
        ),
    ]
