# Generated by Django 5.0.3 on 2024-04-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0005_remove_seat_number_remove_seat_row_seat_seatno'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='category',
            field=models.CharField(choices=[('ADULT', 'Adult'), ('CHILD', 'Child'), ('SENIOR', 'Senior Citizen')], default='ADULT', max_length=10),
        ),
    ]
