# Generated by Django 5.0.3 on 2024-04-08 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0006_seat_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
