# Generated by Django 5.0.3 on 2024-04-08 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0007_remove_booking_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCodeUsage',
        ),
    ]
