# Generated by Django 5.0.3 on 2024-04-11 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0008_delete_promocodeusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='end_time',
        ),
    ]
