# Generated by Django 5.0.3 on 2024-04-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0009_remove_show_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(related_name='bookings', to='theatre.seat'),
        ),
    ]
