# Generated by Django 5.0.3 on 2024-04-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0010_booking_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='encrypted_credit_card_number',
            field=models.BinaryField(default=b'none'),
        ),
        migrations.AddField(
            model_name='booking',
            name='encrypted_cvv',
            field=models.BinaryField(default=b'none'),
        ),
        migrations.AddField(
            model_name='booking',
            name='encrypted_expiry_date',
            field=models.BinaryField(default=b'none'),
        ),
        migrations.AddField(
            model_name='booking',
            name='reference_number',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
